create table travelimage
(
    ImageID        int auto_increment,
    Title          varchar(255)                   null,
    Description    longtext                       null,
    Latitude       double                         null,
    Longitude      double                         null,
    CityCode       int                            null,
    CountryCodeISO varchar(2)                     null,
    UID            int                            null,
    PATH           varchar(225)                   null,
    Content        varchar(255)                   null,
    FAVOR          int          default 0         null,
    Theme          varchar(255) default 'Scenery' null,
    CityName       varchar(255) default ''        null,
    CountryName    varchar(255) default ''        null,
    constraint travelimage_ImageID_uindex
        unique (ImageID)
)
    charset = utf8;

create index CityCode
    on travelimage (CityCode);

create index CountryCodeISO
    on travelimage (CountryCodeISO);

alter table travelimage
    add primary key (ImageID);

INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (1, 'Edworthy Park', 'Calgary Children''s Hospital from Edworthy Park', 51.061249, -114.158077, 5913490, 'CA', 1, '6592902825.jpg', 'scenery', 15, 'People', 'Calgary', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (2, 'Calgary Downtown', 'Calgary Downtown from Edworthy Park', 51.061249, -114.158077, 5913490, 'CA', 1, '6592914823.jpg', 'scenery', 8, 'City', 'Calgary', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (3, 'Grace Presbyterian Church', 'Calgary Beltline during the first snowfall of the season', 51.039522, -114.084236, 5913490, 'CA', 2, '6592317633.jpg', 'scenery', 4, 'Other', 'Calgary', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (4, 'Along the Bow River', 'Along the Bow River in downtown Calgary', 51.051274, -114.082136, 5913490, 'CA', 2, '6592294487.jpg', 'scenery', 1, 'Wonder', 'Calgary', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (5, 'Ascending Sulpher Mountain', 'First time using HDR with 2 stop bracketing composed in PhotoMatix Pro 4.1', 51.149579, -115.559993, 5892532, 'CA', 5, '6114904363.jpg', 'scenery', 2, 'Wonder', 'Banff', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (6, 'At top of Sulpher Mountain', 'At top of Sulpher Mountain near Banff', 51.144571, -115.57467, 5892532, 'CA', 5, '6114907897.jpg', 'scenery', 1, 'Other', 'Banff', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (7, 'Lunenburg Port', 'On board a small sailing ship leaving Lunenburg', 44.373257, -64.307249, 6062069, 'CA', 27, '5856697109.jpg', 'scenery', 5, 'Other', 'Lunenburg', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (8, 'Central United Church', null, 44.377596, -64.309123, 6062069, 'CA', 13, '5856658791.jpg', 'scenery', 2, 'City', 'Lunenburg', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (9, 'Peggy''s Cove', null, 44.491558, -63.91379, null, 'CA', 11, '5856616479.jpg', 'scenery', 3, 'Wonder', '', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (10, 'Near Peggy''s Cove', 'An interesting pile of junk', 44.492859, -63.916676, null, 'CA', 13, '5856654945.jpg', 'scenery', 4, 'Wonder', '', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (11, 'Annapolis Royal', 'Outside the Fort Anne National Historic Site and Museum', 44.741658, -65.519307, null, 'CA', 11, '5857298322.jpg', 'scenery', 5, 'Scenery', '', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (12, 'Near Wolfville, NS', null, 45.093368, -64.360474, null, 'CA', 27, '5857398054.jpg', 'scenery', 9, 'Wonder', '', 'Canada');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (13, 'Central Park', 'Conservatory Pond in Central Park New York', 40.773684, -73.96701, 5128581, 'US', 5, '6596048341.jpg', 'scenery', 6, 'People', 'New York City', 'United States');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (14, 'Rockefeller Center', null, 40.758713, -73.978731, 5128581, 'US', 5, '6596046267.jpg', 'scenery', 3, 'Building', 'New York City', 'United States');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (15, 'Albert Hall', null, 51.500241, -0.177273, 2643743, 'GB', 9, '5855174537.jpg', 'scenery', 4, 'Building', 'London', 'United Kingdom');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (16, 'Emirates Stadium', 'Home to Arsenal FC', 51.556309, -0.107846, 2643743, 'GB', 9, '5855735700.jpg', 'scenery', 4, 'People', 'London', 'United Kingdom');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (17, 'Westminister Abbey', null, 51.49963, -0.128708, 2643743, 'GB', 27, '5855191275.jpg', 'scenery', 6, 'Wonder', 'London', 'United Kingdom');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (18, 'Wellington''s Arch', 'The top of Wellington''s Arch has this sculptural grouping', 51.502572, -0.150869, 2643743, 'GB', 27, '5855752464.jpg', 'scenery', 0, 'Building', 'London', 'United Kingdom');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (19, 'British Museum', 'The library in the British Museum in London', 51.519148, -0.126826, 2643743, 'GB', 27, '5855729828.jpg', 'scenery', 5, 'People', 'London', 'United Kingdom');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (20, 'Castle at Battle, UK', 'Entrance way to the Battle of Hasting''s site in Battle, UK', 50.915115, 0.485893, 2656161, 'GB', 28, '5855774224.jpg', 'scenery', 1, 'People', 'Battle', 'United Kingdom');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (21, 'Lewes Castle', 'Built in 1069, the castle has a tremendous view of the town of Lewes and the surrounding countryside.', 50.872726, 0.008259, 2644559, 'GB', 28, '5855221959.jpg', 'scenery', 1, 'People', 'Lewes', 'United Kingdom');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (22, 'View of Cologne', 'View of Cologne from atop the Cologne Cathedral', 50.941149, 6.957358, 2886242, 'DE', 18, '6114850721.jpg', 'scenery', 2, 'Animal', 'Koeln', 'Germany');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (23, 'Prinz-Georg Garten', null, 49.87872, 8.654719, 2938913, 'DE', 18, '6114859969.jpg', 'scenery', 4, 'Scenery', 'Darmstadt', 'Germany');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (24, 'Downtown Frankfurt', 'Downtown Frankfurt from the Frankfurt Cathedral', 50.110647, 8.684955, 2925533, 'DE', 20, '6114960821.jpg', 'scenery', 5, 'Animal', 'Frankfurt am Main', 'Germany');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (25, 'Brandenburg Gate, Berlin', null, 52.516239, 13.377214, 2950159, 'DE', 10, '6114881215.jpg', 'scenery', 2, 'People', 'Berlin', 'Germany');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (26, 'Outside the Berliner Dom', null, 52.519255, 13.399552, 2950159, 'DE', 10, '6115603234.jpg', 'scenery', 4, 'Scenery', 'Berlin', 'Germany');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (27, 'New National Gallery, Ber', 'Exterior of the Mies van der Rohe designed New National Gallery', 52.506482, 13.367899, 2950159, 'DE', 10, '6114867983.jpg', 'scenery', 1, 'Building', 'Berlin', 'Germany');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (28, 'Checkpoint Charlie', null, 52.507324, 13.390419, 2950159, 'DE', 10, '6115548152.jpg', 'scenery', 2, 'Other', 'Berlin', 'Germany');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (29, 'Plaza de Cibeles, Madrid', null, 40.419098, -3.692452, 3117735, 'ES', 29, '5855209453.jpg', 'scenery', 6, 'Building', 'Madrid', 'Spain');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (30, 'Santiago Bernabeu, Madrid', 'Home stadium for Real Madrid', 40.452891, -3.689813, 3117735, 'ES', 29, '5855213165.jpg', 'scenery', 2, 'Scenery', 'Madrid', 'Spain');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (31, 'Paradise Island in Nassau', 'Photographed from Atlantis Bridge; Paradise Island in Nassau, Bahamas', 25.077709, -77.324127, 3571824, 'BS', 30, '6119127716.jpg', 'scenery', 5, 'People', 'Nassau', 'Bahamas');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (32, 'Castaway Cay, South Abaco', null, 26.082139, -77.536223, null, 'BS', 30, '6119130918.jpg', 'scenery', 6, 'City', '', 'Bahamas');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (33, 'Disney Coronado Resort', null, 28.365272, -81.572183, 4167147, 'US', 6, '6119143988.jpg', 'scenery', 3, 'Wonder', 'Orlando', 'United States');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (34, 'Beach in Ghana', null, null, null, null, 'GH', 3, '8152043422.jpg', 'scenery', 5, 'Building', '', 'Ghana');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (35, 'Beach in Ghana', null, null, null, null, 'GH', 3, '8152016381.jpg', 'scenery', 4, 'People', '', 'Ghana');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (36, 'Cape Coast', null, 5.104149, -1.240446, 2302357, 'GH', 3, '8152045688.jpg', 'scenery', 4, 'City', 'Cape Coast', 'Ghana');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (37, 'Cape Coast', null, 5.103262, -1.240816, 2302357, 'GH', 3, '8152045872.jpg', 'scenery', 3, 'Animal', 'Cape Coast', 'Ghana');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (38, 'Cape Coast', null, 5.103367, -1.241535, 2302357, 'GH', 3, '8152020963.jpg', 'scenery', 1, 'Animal', 'Cape Coast', 'Ghana');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (39, 'Accra', null, null, null, 2306104, 'GH', 3, '8152048712.jpg', 'scenery', 1, 'Animal', 'Accra', 'Ghana');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (40, 'Florence', null, 43.766069, 11.252747, 3176959, 'IT', 27, '222222.jpg', 'scenery', 6, 'Other', 'Firenze', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (41, 'Milan', null, 45.442661, 9.20105, 3173435, 'IT', 27, '222223.jpg', 'scenery', 5, 'Building', 'Milano', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (42, 'Verona Building Art', 'Verona Building Art', 45.442871, 10.997508, 3164527, 'IT', 17, '9493997865.jpg', 'scenery', 8, 'Wonder', 'Verona', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (43, 'Verona Ponte Scaligero', null, 45.441069, 10.987755, 3164527, 'IT', 17, '9496787858.jpg', 'scenery', 3, 'People', 'Verona', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (44, 'Verona Piazza Bra at Night', null, 45.438794, 10.993353, 3164527, 'IT', 17, '9496792166.jpg', 'scenery', 2, 'Other', 'Verona', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (45, 'Verona', 'Near Ponte Nuovo', 45.443997, 11.000893, 3164527, 'IT', 17, '9496799098.jpg', 'scenery', 5, 'People', 'Verona', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (46, 'Prato della Valle', 'Prato della Valle in Padova', 45.398611, 11.875797, 3171728, 'IT', 17, '9494282329.jpg', 'scenery', 2, 'City', 'Padova', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (47, 'St Marks Square in Venice', null, 45.434233, 12.338693, 3164603, 'IT', 8, '9494475161.jpg', 'scenery', 2, 'Building', 'Venezia', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (48, 'Santa Maria della Salute, Venice', null, 45.431003, 12.334766, 3164603, 'IT', 8, '9494472443.jpg', 'scenery', 6, 'Animal', 'Venezia', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (49, 'Venice View From Ponte di Rialto', null, 45.437975, 12.335871, 3164603, 'IT', 8, '9494464567.jpg', 'scenery', 1, 'Scenery', 'Venezia', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (50, 'Venice', null, 45.435124, 12.328055, 3164603, 'IT', 8, '9494470337.jpg', 'scenery', 3, 'People', 'Venezia', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (51, 'Montepulciano', null, 43.092535, 11.782022, 3172794, 'IT', 8, '9496560520.jpg', 'scenery', 0, 'Scenery', 'Montepulciano', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (52, 'Arch of Constantine', 'view from within the Colosseum', 41.88983, 12.490873, 3169070, 'IT', 17, '9498368556.jpg', 'scenery', 2, 'City', 'Roma', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (53, 'Inside the Colosseum', null, 41.890332, 12.49181, 3169070, 'IT', 17, '9495571869.jpg', 'scenery', 3, 'Animal', 'Roma', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (54, 'Arch of Septimus Severus', 'In the Roman Forum', 41.892949, 12.484972, 3169070, 'IT', 17, '9495574327.jpg', 'scenery', 2, 'Animal', 'Roma', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (55, 'Palatine Hill', 'Walking up the via di San Gregorio side of the Hill', 41.887437, 12.48866, 3169070, 'IT', 17, '9498381010.jpg', 'scenery', 1, 'City', 'Roma', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (56, 'From St. Peters', null, 41.902172, 12.456098, 3169070, 'IT', 17, '9498386718.jpg', 'scenery', 2, 'City', 'Roma', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (57, 'Temple of Asclepius', 'In the Villa Borghese Park', 41.914541, 12.483443, 3169070, 'IT', 4, '9498388516.jpg', 'scenery', 2, 'Scenery', 'Roma', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (58, 'Florence Duomo', 'Photo taken from the Campanile', 43.772801, 11.255673, 3176959, 'IT', 22, '9498358806.jpg', 'scenery', 2, 'City', 'Firenze', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (59, 'Orpheus Fountain, Florence', 'In the garden of Palazzo Vivarelli Colonna', 43.76964, 11.266535, 3176959, 'IT', 22, '9504606628.jpg', 'scenery', 3, 'Other', 'Firenze', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (60, 'Pazzi Chapel at Santa Croce', 'By Filippo Brunelleschi, the chapel is considered to be one of the masterpieces of Renaissance architecture. It is located in the first cloister of the Basilica di Santa Croce.', 43.768234, 11.262212, 3176959, 'IT', 22, '9504609042.jpg', 'scenery', 1, 'People', 'Firenze', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (61, 'Palazzo Strozzi, Florence', null, 43.771339, 11.251678, 3176959, 'IT', 12, '9504613978.jpg', 'scenery', 2, 'People', 'Firenze', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (62, 'Interior Santo Spirito, Florence', 'Filippo Brunelleschi designed church has been called by Bernini the most beautiful church in the world. I have to concur with the master, it is beyond stunning …', 43.767212, 11.248202, 3176959, 'IT', 12, '9504451722.jpg', 'scenery', 0, 'Other', 'Firenze', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (63, 'Santo Spirito, Florence', null, 43.766827, 11.248174, 3176959, 'IT', 12, '9504449928.jpg', 'scenery', 2, 'Animal', 'Firenze', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (64, 'Garden of Boboli, Pitti Palace, Florence', null, 43.763791, 11.251147, 3176959, 'IT', 15, '9504448540.jpg', 'scenery', 4, 'Building', 'Firenze', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (65, 'Santa Maria Novella, Florence', null, 43.773933, 11.249692, 3176959, 'IT', 15, '9504445110.jpg', 'scenery', 5, 'Animal', 'Firenze', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (66, 'Camposanto, Pisa', null, 43.724017, 10.394762, 3170647, 'IT', 15, '9505536014.jpg', 'scenery', 3, 'Wonder', 'Pisa', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (67, 'Cathedral, Pisa', null, 43.723039, 10.394697, 3170647, 'IT', 23, '9502740177.jpg', 'scenery', 4, 'Animal', 'Pisa', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (68, 'Pisa Cathedral from Leaning Tower', null, 43.722977, 10.396661, 3170647, 'IT', 23, '9502741759.jpg', 'scenery', 3, 'Other', 'Pisa', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (69, 'San Michele in Foro, Lucca', null, 43.842953, 10.502501, 3174530, 'IT', 23, '9505893300.jpg', 'scenery', 3, 'Building', 'Lucca', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (70, 'Basilica of San Frediano, Lucca', null, 43.845901, 10.505397, 3174530, 'IT', 23, '9505897492.jpg', 'scenery', 3, 'City', 'Lucca', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (71, 'Matthias Church', 'Official name is "Church of the Blessed Virgin in Buda". Central part of church built around 1400, with additions by Turks, and then Baroque-era modifications, finally redone in late 19th Century in neo-Gothic revival. Very much a masterpiece of European eclecticism, though some say it is an over-decorated piece of stage scenery.', 47.502449, 19.03453, 3054643, 'HU', 7, '8730408907.jpg', 'scenery', 3, 'Scenery', 'Budapest', 'Hungary');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (72, 'St. Stephen''s Cathedral', null, 47.500742, 19.053246, 3054643, 'HU', 7, '8731523536.jpg', 'scenery', 6, 'Scenery', 'Budapest', 'Hungary');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (73, 'Ekklisia Agii Isidori church', 'At the top of the Lycabettus Hill', 37.981905, 23.743295, 264371, 'GR', 14, '8710320515.jpg', 'scenery', 3, 'Animal', 'Athens', 'Greece');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (74, 'Temple of Hephaistos', 'Located on western perimeter of Agora in Athens. Built in 460-415 BCE, it is the best preserved temple of antiquity.', 37.975579, 23.721526, 264371, 'GR', 14, '8711645510.jpg', 'scenery', 3, 'Wonder', 'Athens', 'Greece');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (75, 'Ancient Theatre of Dionysos', 'On south bank of Acropolis', 37.970657, 23.727309, 264371, 'GR', 14, '8710513053.jpg', 'scenery', 1, 'People', 'Athens', 'Greece');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (76, 'Roman Agora', null, 37.974157, 23.726703, 264371, 'GR', 12, '8711623884.jpg', 'scenery', 6, 'Wonder', 'Athens', 'Greece');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (77, 'Dusk on Imerovigli (Santorini)', 'Looking towards Imerovigli, a village devoted to the appreciation of the sunset!', 36.429988, 25.426145, 252920, 'GR', 12, '8710247776.jpg', 'scenery', 4, 'People', 'Fira', 'Greece');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (78, 'Looking towards Fira', null, 36.42898, 25.426612, 252920, 'GR', 12, '8710289254.jpg', 'scenery', 4, 'Other', 'Fira', 'Greece');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (80, 'Gresham Palace', 'Built in early 20th century and originally the headquarters for an English insurance company. Nationalized after the war, it was turned into a Four Season''s Hotel after a 100 million dollar renovation from 2000-2004. Evidently one of the world''s swankiest hotels. It overlooks Roosevelt Square and the Chain Bridge.', 47.49972, 19.04753, 3054643, 'HU', 7, '8731526170.jpg', 'scenery', 3, 'Other', 'Budapest', 'Hungary');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (81, 'Christ Church College, Oxford', null, 51.749364, -1.255794, 2640729, 'GB', 21, '8645912379.jpg', 'scenery', 3, 'Wonder', 'Oxford', 'United Kingdom');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (82, 'Cloisters, New College, Oxford', null, 51.754369, -1.252417, 2640729, 'GB', 21, null, 'scenery', 5, 'City', 'Oxford', 'United Kingdom');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (83, 'gdr3312', 'sefsfVSFAF234', null, null, 3164527, 'IT', 32, '85.jpg', null, 0, 'Building', 'Verona', 'Italy');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (84, 'tydhnfgx', 'gdgtrdt', null, null, 2925533, 'DE', 32, '运行SonarQube.jpeg', null, 0, 'Scenery', 'Frankfurt am Main', 'Germany');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (85, 'ewrfwef', 'gergege', null, null, 2302357, 'GH', 32, '单元测试.jpeg', null, 0, 'People', 'Cape Coast', 'Ghana');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (86, 'sfgFSDF', 'FEDRTH', null, null, 2644559, 'GB', 32, '92.jpg', null, 0, 'People', 'Lewes', 'United Kingdom');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (87, 'ewrfwe', 'gertger', null, null, 4167147, 'US', 32, '未命名文件.png', null, 0, 'Wonder', 'Orlando', 'United States');
INSERT INTO travel.travelimage (ImageID, Title, Description, Latitude, Longitude, CityCode, CountryCodeISO, UID, PATH, Content, FAVOR, Theme, CityName, CountryName) VALUES (88, 'asdffrw', 'uiklouy', null, null, 3054643, 'HU', 33, '71.jpg', null, 0, 'Wonder', 'Budapest', 'Hungary');